### ISSUE TITLE
Error while uploading

### ISSUE THREAD

**Issue by zumek** [InteractiveAdvertisingBureau/HTML5-AdValidator#15]
Receiving the following error when trying to upload - An error occurred on the server. Please check your inputs.

The inputs were the ZIP of the ad and the project name. Unsure of what else to check. This issue started to occur today, as far as I know. It was working yesterday.

**Comment by goosemanjack** [comment]
I am looking into this issue. Will update this thread when I have more
information.
--
clc

**Comment by goosemanjack** [comment]
The root cause was a disk space issue. I have removed old files and the system is not back online and available for use.
