### ISSUE TITLE
Validator not displaying results

### ISSUE THREAD

**Issue by pinkblink32** [InteractiveAdvertisingBureau/HTML5-AdValidator#16]
Hi there, 
It looks like the validator is no longer working, can you take a look please?  When I load a tag to check, the results come up blank.  

Thanks!
Heather

**Comment by goosemanjack** [comment]
Looking into it now. Will post when I have more info.
--
clc

**Comment by goosemanjack** [comment]
Resolved as a disk space issue. The validator is now working again. Thanks for your report, and you should be back online.
