### ISSUE TITLE
Validator not presenting results

### ISSUE THREAD

**Issue by pinkblink32** [InteractiveAdvertisingBureau/HTML5-AdValidator#17]
Hi there, 
The Validator is coming up with blank results again.  This happened a few months ago I think due to memory, can you fix it again?

Thanks so much!
Cheers, 
Heather

**Comment by goosemanjack** [comment]
Thank you for reporting this. We are actively troubleshooting and will update as we have more information.

**Comment by goosemanjack** [comment]
We believe this issue has been resolved. Results are now presenting. If the behavior starts again please re-open this ticket.

**Comment by iabmayank** [comment]
Hello,

Apologize for the inconvenience and thanks for notifying us. We have fixed the issue and also working on making error notifications more robust.

Thanks,
-----------------------
Mayank Mishra
Senior Director, Engineering
116 East 27th Street, 7th Floor,
New York, New York 10016
Office 212.378.4292
Cell 201.210.9699
Skype @maymishra
[Description: Description: cid:image001.png@01CB9864.6EC69250]

**Comment by pinkblink32** [comment]
No worries, thanks for the quick fix and providing the service in the first
place!

Cheers,
Heather

**Comment by pinkblink32** [comment]
Hi there,
It seems the validator is down again as we are getting a 404 Error when we
visit the site.  Are you able to get it back up and running?

Thanks!
Heather

**Comment by goosemanjack** [comment]
What URL are you attempting to access?
This is the correct URL:   [https://html5.iabtechlab.com/secure](https://html5.iabtechlab.com/secure)

We recently cleaned and updated our infrastructure. In the process it was noticed that some parties were still using the Alpha URL at platform.iabtechlab.com. This is not a valid URL and you should update all your tools and links.

I have just validated both ad tags and zip packages are renderings. If after updating your URLs you still experience this issue, please open a new ticket and we will investigate.


--
clc

**Comment by goosemanjack** [comment]
PS. Sorry for yelling. Not sure what happened in the markdown.
--
clc

**Comment by pinkblink32** [comment]
Hi Chris,
That seemed to be the issue, thanks for your help, it's working now!

Heather
